app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$uploadFile(datafile = "../Exam.csv") # <-- This should be the path to the file, relative to the app's tests/ directory
app$setInputs(dv = "normexam")
app$snapshot()
app$setInputs(l1 = "standLRT")
app$snapshot()
app$setInputs(l1_varies = "standLRT")
app$snapshot()
app$setInputs(l2 = "type")
app$snapshot()
app$setInputs(interaction = "standLRT:type")
app$snapshot()
app$setInputs(l2 = character(0))
app$snapshot()
app$setInputs(l2 = "type")
app$setInputs(interaction = "standLRT:type")
app$setInputs(l1_varies = character(0))
app$snapshot()
app$setInputs(l1_varies = "standLRT")
app$setInputs(interaction = "standLRT:type")
app$setInputs(l1 = character(0))
Sys.sleep(0.5) # otherwise the interface is too slow to react
app$snapshot()
