app <- ShinyDriver$new("../")
app$snapshotInit("formula")

app$uploadFile(datafile = "hsball.csv") # <-- This should be the path to the file, relative to the app's tests/ directory
app$setInputs(dv = "MATHACH")
app$setInputs(l1 = "FEMALE")
app$setInputs(l1 = c("FEMALE", "SES"))
app$setInputs(l1 = c("MINORITY", "FEMALE", "SES"))
app$setInputs(l1_varies = "MINORITY")
app$setInputs(l2 = "SIZE")
app$setInputs(l2 = c("SIZE", "SECTOR"))
app$setInputs(interaction = "MINORITY:SIZE")
app$setInputs(interaction = c("MINORITY:SIZE", "MINORITY:SECTOR"))
app$setInputs(l1_varies = c("MINORITY", "FEMALE"))
app$setInputs(l1_varies = "MINORITY")
app$snapshot()
