app <- ShinyDriver$new("../")
app$snapshotInit("mlmRev")

app$uploadFile(datafile = "exam2.csv") # <-- This should be the path to the file, relative to the app's tests/ directory
app$setInputs(dv = "normexam")
app$setInputs(l1 = "female")
app$setInputs(l2 = "schgendmixed")
app$setInputs(l2 = c("schgendmixed", "schgendboys"))
app$setInputs(l1 = c("standLRT", "female"))
app$snapshot()
app$setInputs(l2 = "schgendboys")
app$setInputs(l2 = character(0))
app$setInputs(l2 = "type")
app$snapshot()
app$setInputs(l1_varies = "standLRT")
app$snapshot()
app$setInputs(l1 = c("standLRT", "sex", "female"))
app$setInputs(l1 = c("standLRT", "female"))
app$setInputs(l1_varies = c("standLRT", "female"))
app$snapshot()
